apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hrw-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.org/client-max-body-size: 30m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: hrw-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hrw-svc
            port:
              number: 80
