apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    owner: z8
    project: hrw
    business-unit: hr
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-5fa65d2
    app.kubernetes.io/version: "5.04"
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: hrw
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app: redis
  replicas: {{ .Values.redis.replicas }}
  template:
    metadata:
      labels:
        app: redis
        owner: z8
        project: hrw
        business-unit: hr
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: redis-5fa65d2
        app.kubernetes.io/version: "5.04"
        app.kubernetes.io/component: cache
        app.kubernetes.io/part-of: hrw
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - name: redis
        image:  {{ .Values.redis.image }}
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "1Gi"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config
            items:
            - key: redis-config
              path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
data:
  redis-config: |
    maxmemory 200mb
    maxmemory-policy allkeys-lru