{{ if eq .Values.environment.type "onprem" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.repository.persistentVolume }}
  namespace: {{ .Values.namespace }}
  labels:
    type: {{ .Values.repository.persistentVolume }}
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.repository.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hrw-repository-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.repository.size }}
  selector: 
    matchLabels:
      type: {{ .Values.repository.persistentVolume }}
{{ end }}